### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by iProgYou** [eismatthew/cloundsoud#2]
# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`
## Comments
- It is probably not that necessary to have an email and a username. Likely you only need one, but it is up to you.
- Make sure to back-tick the column names

**Comment by eismatthew** [comment]
Removed email parameter (keeping username for now)
Fixed formatting for column names

**Comment by iProgYou** [comment]
Lets talk about email
